# Generated by Django 2.1.3 on 2018-11-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailer_second_mail', models.EmailField(max_length=254)),
                ('mailer_company', models.CharField(max_length=250)),
                ('mailer_company_address', models.CharField(max_length=250)),
                ('mailer_phone_number', models.CharField(max_length=30)),
                ('mailer_company_industry', models.CharField(max_length=250)),
                ('mailer_company_website', models.CharField(max_length=250)),
                ('mailer_user_status', models.CharField(choices=[('NCN', 'Not confirmed mail'), ('MCN', 'Confirmed mail'), ('ACN', 'Admin confirmed')], default='NCN', max_length=3, verbose_name='user status')),
                ('mailer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
