# Generated by Django 2.0.8 on 2018-11-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_file', models.FileField(blank=True, null=True, upload_to='attached_files/2018/11/25')),
            ],
            options={
                'verbose_name_plural': 'Attached Campaigns Files',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_description', models.TextField(max_length=1500)),
                ('campaign_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='DomainBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Domains Black List',
            },
        ),
        migrations.CreateModel(
            name='MailerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailer_company', models.CharField(max_length=250)),
                ('mailer_company_address', models.CharField(max_length=250)),
                ('mailer_phone_number', models.CharField(max_length=30)),
                ('mailer_company_industry', models.CharField(max_length=250)),
                ('mailer_company_website', models.CharField(max_length=250)),
                ('mailer_user_status', models.CharField(choices=[('NCN', 'Not confirmed mail'), ('MCN', 'Confirmed mails'), ('ACN', 'Admin confirmed')], default='NCN', max_length=3, verbose_name='user status')),
                ('mailer_account_type', models.CharField(choices=[('FREE', 'Free account'), ('PREM', 'Premium account')], default='FREE', max_length=4, verbose_name='account type')),
            ],
            options={
                'verbose_name_plural': 'Users List',
            },
        ),
        migrations.CreateModel(
            name='UserEmails',
            fields=[
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_emails', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mailer_first_email', models.EmailField(max_length=100, unique=True)),
                ('mailer_first_email_status', models.BooleanField(default=False)),
                ('mailer_second_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mailer_second_email_status', models.BooleanField(default=False)),
                ('mailer_with_single_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users Emails List',
            },
        ),
        migrations.CreateModel(
            name='UserSavedCampaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_campaign_sent_status', models.BooleanField(default=False)),
                ('saved_campaign_sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_campaign', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='saved_campaign', to='Sender.Campaign')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Saved Campaigns',
            },
        ),
        migrations.AddField(
            model_name='maileruser',
            name='mailer_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachedfiles',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_files', to='Sender.Campaign'),
        ),
    ]
