# Generated by Django 2.0.8 on 2018-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfiles',
            name='campaign_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_attached_files/2018/11/25'),
        ),
    ]
