# Generated by Django 2.1.3 on 2018-11-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailer_first_email', models.EmailField(max_length=100, unique=True)),
                ('mailer_first_email_status', models.BooleanField()),
                ('mailer_second_email', models.EmailField(max_length=100, unique=True)),
                ('mailer_second_email_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='maileruser',
            name='mailer_emails',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='Sender.UserEmails'),
        ),
    ]
