# Generated by Django 2.1.3 on 2018-11-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0003_domainblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremails',
            name='mailer_first_email_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useremails',
            name='mailer_second_email_status',
            field=models.BooleanField(default=False),
        ),
    ]
