# Generated by Django 2.1.3 on 2018-11-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0004_auto_20181109_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maileruser',
            name='mailer_second_mail',
        ),
    ]
