# Generated by Django 2.1.3 on 2018-11-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0005_remove_maileruser_mailer_second_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maileruser',
            name='mailer_emails',
        ),
        migrations.AddField(
            model_name='useremails',
            name='mailer_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='Sender.MailerUser'),
        ),
    ]
