# Generated by Django 2.1.3 on 2018-11-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0009_auto_20181110_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremails',
            old_name='mailer_user',
            new_name='user',
        ),
    ]
