# Generated by Django 2.1.3 on 2018-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0010_auto_20181110_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maileruser',
            name='mailer_user_status',
            field=models.CharField(choices=[('NCN', 'Not confirmed mail'), ('MCN', 'Confirmed mails'), ('ACN', 'Admin confirmed')], default='NCN', max_length=3, verbose_name='user status'),
        ),
        migrations.AlterField(
            model_name='useremails',
            name='mailer_second_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
