# Generated by Django 2.1.3 on 2018-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0011_auto_20181120_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremails',
            name='mailer_with_single_email',
            field=models.BooleanField(default=False),
        ),
    ]
