# Generated by Django 2.1.3 on 2018-11-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0017_auto_20181120_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
