# Generated by Django 2.1.3 on 2018-11-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0018_auto_20181120_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='email_header',
            field=models.CharField(default='Mail from mailsender', max_length=50),
        ),
    ]
