# Generated by Django 2.0.8 on 2018-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0020_auto_20181120_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user_message_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user_message_name',
            field=models.CharField(max_length=100),
        ),
    ]
