# Generated by Django 2.0.8 on 2018-11-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0022_auto_20181121_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainblacklist',
            options={'verbose_name_plural': 'Domains Black List'},
        ),
        migrations.AlterModelOptions(
            name='maileruser',
            options={'verbose_name_plural': 'Users List'},
        ),
        migrations.AlterModelOptions(
            name='useremails',
            options={'verbose_name_plural': 'Users Emails List'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name_plural': 'Users Messages'},
        ),
    ]
