# Generated by Django 2.0.8 on 2018-11-21 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sender', '0024_auto_20181121_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmails',
            new_name='Сampaigns',
        ),
    ]
