# Generated by Django 2.0.8 on 2018-11-21 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0027_auto_20181121_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_campaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
