# Generated by Django 2.0.8 on 2018-11-21 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('Sender', '0028_auto_20181121_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Campaign',
        ),
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='UserEmails',
        ),
    ]
