# Generated by Django 2.0.8 on 2018-11-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0030_auto_20181122_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attached_files'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='attached_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_files', to='Sender.AttachedFiles'),
        ),
    ]
