# Generated by Django 2.0.8 on 2018-11-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0031_auto_20181122_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='attached_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_files', to='Sender.AttachedFiles'),
        ),
    ]
