# Generated by Django 2.0.8 on 2018-11-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0032_auto_20181122_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='attached_files',
        ),
        migrations.AddField(
            model_name='attachedfiles',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_files', to='Sender.Campaign'),
        ),
    ]
