# Generated by Django 2.0.8 on 2018-11-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sender', '0033_auto_20181122_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedMessages',
            fields=[
                ('saved_campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saved_campaign', serialize=False, to='Sender.Campaign')),
                ('campaign_sent_status', models.BooleanField(default=False)),
                ('campaign_sent_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Saved Campaigns',
            },
        ),
    ]
