# Generated by Django 2.0.8 on 2018-11-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0035_auto_20181122_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_description',
            field=models.TextField(max_length=1500),
        ),
    ]
