# Generated by Django 2.0.8 on 2018-11-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0036_auto_20181122_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedcampaigns',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersavedcampaigns',
            name='saved_campaign',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='saved_campaign', to='Sender.Campaign'),
        ),
    ]
