# Generated by Django 2.0.8 on 2018-11-23 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0038_auto_20181123_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedfiles',
            old_name='file',
            new_name='campaign_file',
        ),
    ]
