# Generated by Django 2.0.8 on 2018-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sender', '0039_auto_20181123_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfiles',
            name='campaign_file',
            field=models.FileField(blank=True, null=True, upload_to='attached_files/2018/11/23'),
        ),
    ]
